spring.application.name=joueur-service
server.port=8081

# PostgreSQL - base de donnees dediee a CE microservice uniquement
spring.datasource.url=jdbc:postgresql://localhost:5432/motus_joueur
spring.datasource.username=motus
spring.datasource.password=motus
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
server.error.include-message=always
