apiVersion: v1
kind: Secret
metadata:
  name: motus-db
type: Opaque
stringData:
  POSTGRES_USER: motus
  POSTGRES_PASSWORD: motus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init-databases.sql: |
    CREATE DATABASE motus_joueur OWNER motus;
    CREATE DATABASE motus_partie OWNER motus;
    CREATE DATABASE motus_score  OWNER motus;
